#pragma config(Motor,  port1,           LiftR,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Fly1R,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Fly1L,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

bool intake = false;
task main()
{
	while(1){

		//Lower Intake
		if(vexRT[Btn5U] == 1)
		{
			motor[Fly1R]= 70;
			motor[Fly1L] =  -70;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[Fly1R]= -70;
			motor[Fly1L] =  70;
		}
		else{
			motor[Fly1R]= 0;
			motor[Fly1L] =  0;
		}
		//Glyph Lift
		if((vexRT[Btn7U] == 1))
		{
			motor[LiftR]= 70;
			motor[LiftL] =  -70;
		}
		else if((vexRT[Btn7D] == 1))
		{
			motor[LiftR]= -70;
			motor[LiftL] =  70;
		}
		else{
			motor[LiftR]= 0;
			motor[LiftL] =  0;
		}

		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}


}
