#pragma config(Sensor, in1,    POT,            sensorPotentiometer)
#pragma config(Motor,  port1,           BackR,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           HMotor,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FrontL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CLAW,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LARM,          tmotorNone, openLoop)
#pragma config(Motor,  port7,           RARM,          tmotorNone, openLoop)
#pragma config(Motor,  port10,          BackL,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

#define downPOS 3132
#define upPOS 1440

int armMode = 0;
float armTarget;

task runClaw()
{
	while(1){
		//Run Claw
		if((vexRT[Btn6U] == 1))
		{
			motor[CLAW]= 70;
		}
		else if((vexRT[Btn6D] == 1))
		{
			motor[CLAW]= -70;
		}
		else{
			motor[CLAW] = 0;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

//Task to Manage Claw Lift Position
task clawLift()
{
	armTarget = SensorValue[POT];
	float proportionalCoefficient = 0.2;
	float error,
	motorPower,
	proportional; //what you set the motors to
	while (true)
	{
		//ENABLE PID
		if(armMode==1){
			error = armTarget - SensorValue[POT];
			proportional = error * proportionalCoefficient;
			motorPower = proportional;
			motor[RARM] = motorPower;
			motor[LARM] = motorPower;
		}
		//DISABLE PID
		else if(armMode==0){
			//Arm UP
			if(vexRT[Btn5U] == 1)
			{
				motor[RARM] = -127;
				motor[LARM] = -127;
			}
			//Arm Down
			else if(vexRT[Btn5D] == 1)
			{
				motor[RARM] =110;
				motor[LARM] = 110;
			}
			//Arm Stop
			else{
				armTarget = SensorValue[POT];
				armMode = 1;
			}
			// Motor values can only be updated every 20ms
			wait1Msec(20);
		}
	}
}


task hDrive() {
	while(true) {
		motor[FrontL]  = C1LX + C1LY;
		motor[FrontR] = C1LX - C1LY;
		motor[BackL]  = C1LX + C1LY;
		motor[BackR] = C1LX - C1LY;
		motor[HMotor] = C1RX ;
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task main(){
	startTask(hDrive);
	startTask(clawLift);
	startTask(runClaw);
	while(true) {
				//Move Arm
		if(vexRT[Btn5U] == 1)
		{
			armMode = 0;
		}
		else if(vexRT[Btn5D] == 1)
		{
			armMode = 0;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}
