#pragma config(Sensor, in1,    POT,            sensorPotentiometer)
#pragma config(Sensor, in2,    CLAWPOT,        sensorPotentiometer)
#pragma config(Motor,  port1,           BackR,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           HMotor,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FrontL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CLAW,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LARM,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RARM,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BackL,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

#define downPOS 1063
#define upPOS 2025

#define clawOpen 950
#define clawClose 250

int armMode = 0;
float armTarget;

int clawMode = 0;
float clawTarget;

//Run CLaw
task runClaw()
{
	clawMode = 1;
	clawTarget = SensorValue[CLAWPOT];
	float proportionalCoefficient = -0.035;
	float error,
	motorPower,
	proportional; //what you set the motors to
	while (true)
	{
		error = clawTarget - SensorValue[CLAWPOT];
		proportional = error * proportionalCoefficient;
		if(proportional<0){
			motorPower = proportional;
		}
		else{
			motorPower = proportional+30;
		}
		motor[CLAW] = motorPower;
		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}

//Task to Manage Claw Lift Position
task runLift()
{
	armTarget = downPOS+20;
	armMode = 1;
	float proportionalCoefficient = -0.07;
	float error,
	motorPower,
	proportional; //what you set the motors to
	while (true)
	{
		//ENABLE PID
		if(armMode==1){
			error = armTarget - SensorValue[POT];
			proportional = error * proportionalCoefficient;
			motorPower = proportional;
			motor[RARM] = motorPower;
			motor[LARM] = motorPower;
		}
		//DISABLE PID
		else if(armMode==0){
			if(vexRT[Btn5U] == 1)
			{
				motor[RARM] = -100;
				motor[LARM] = -100;
			}
			//Arm Down
			else if(vexRT[Btn5D] == 1)
			{
				motor[RARM] =90;
				motor[LARM] = 90;
			}
			//Arm Stop
			else{
				armTarget = SensorValue[POT];
				armMode = 1;
			}
			// Motor values can only be updated every 20ms
			wait1Msec(20);
		}
	}
}


task hDrive() {
	while(true) {
		motor[FrontL]  = C1LX + C1LY;
		motor[FrontR] = C1LX - C1LY;
		motor[BackL]  = C1LX + C1LY;
		motor[BackR] = C1LX - C1LY;
		motor[HMotor] = C1RX ;
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task arcadeDrive() {
	while(true) {
		motor[FrontL]  = C1RX + C1LY;
		motor[FrontR] = C1RX - C1LY;
		motor[BackL]  = C1RX + C1LY;
		motor[BackR] = C1RX - C1LY;
		if(vexRT[Btn7L]){
			motor[HMotor] =  -80;
		}
		else if(vexRT[Btn7R]){
			motor[HMotor] =  80;
		}
		else{
			motor[HMotor] = 0;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task main(){
	startTask(arcadeDrive);
	startTask(runLift);
	startTask(runClaw);
	while(true) {
		//Move Arm
		if(vexRT[Btn5U] == 1)
		{
			armMode = 0;
		}
		else if(vexRT[Btn5D] == 1)
		{
			armMode = 0;
		}
		//Move Claw
		if(vexRT[Btn6U] == 1)
		{
			clawTarget = clawOpen;
		}
		else if(vexRT[Btn6D] == 1)
		{
			clawTarget = clawClose;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}
