#pragma config(Sensor, in1,    POT,            sensorPotentiometer)
#pragma config(Sensor, in2,    CLAWPOT,        sensorPotentiometer)
#pragma config(Motor,  port1,           BackR,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           HMotor,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FrontL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LARM,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RARM,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LIFT,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           FLY,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          BackL,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

#define downPOS 1063
#define upPOS 2025

int armMode = 0;
float armTarget;

//Run Flywheels
task runFlywheel()
{
	while (true)
	{
		//Lower Intake
		if(vexRT[Btn5U] == 1)
		{
			motor[FLY]= 70;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[FLY]= -70;
		}
		else{
			motor[FLY]= 0;
		}

		//Glyph Lift
		if((vexRT[Btn6U] == 1))
		{
			motor[LIFT]= 100;
		}
		else if((vexRT[Btn6D] == 1))
		{
			motor[LIFT]= -100;
		}
		else{
			motor[LIFT]= 0;
		}

		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}

//Task to Manage Claw Lift Position
task runLift()
{
	armTarget = downPOS+20;
	armMode = 1;
	float proportionalCoefficient = -0.07;
	float error,
	motorPower,
	proportional; //what you set the motors to
	while (true)
	{
		//ENABLE PID
		if(armMode==1){
			error = armTarget - SensorValue[POT];
			proportional = error * proportionalCoefficient;
			motorPower = proportional;
			motor[RARM] = motorPower;
			motor[LARM] = motorPower;
		}
		//DISABLE PID
		else if(armMode==0){
			if(vexRT[Btn5U] == 1)
			{
				motor[RARM] = -100;
				motor[LARM] = -100;
			}
			//Arm Down
			else if(vexRT[Btn5D] == 1)
			{
				motor[RARM] =90;
				motor[LARM] = 90;
			}
			//Arm Stop
			else{
				armTarget = SensorValue[POT];
				armMode = 1;
			}
			// Motor values can only be updated every 20ms
			wait1Msec(20);
		}
	}
}


task hDrive() {
	while(true) {
		motor[FrontL]  = C1LX + C1LY;
		motor[FrontR] = C1LX - C1LY;
		motor[BackL]  = C1LX + C1LY;
		motor[BackR] = C1LX - C1LY;
		motor[HMotor] = C1RX ;
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task main(){
	startTask(hDrive);
	//startTask(runLift);
	startTask(runFlywheel);
	while(true) {
		//Move Arm
		if(vexRT[Btn5U] == 1)
		{
			armMode = 0;
		}
		else if(vexRT[Btn5D] == 1)
		{
			armMode = 0;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}
