#pragma config(Motor,  port1,           BackR,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           HMotor,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FrontL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Fly1L,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LiftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Fly1R,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BackL,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

task flyLift()
{
	while(1){

		//Lower Intake
		if(vexRT[Btn5U] == 1)
		{
			motor[Fly1R]= 70;
			motor[Fly1L] =  -70;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[Fly1R]= -70;
			motor[Fly1L] =  70;
		}
		else{
			motor[Fly1R]= 0;
			motor[Fly1L] =  0;
		}
		//Glyph Lift
		if((vexRT[Btn6U] == 1))
		{
			motor[LiftR]= 70;
			motor[LiftL] =  -70;
		}
		else if((vexRT[Btn6D] == 1))
		{
			motor[LiftR]= -70;
			motor[LiftL] =  70;
		}
		else{
			motor[LiftR]= 0;
			motor[LiftL] =  0;
		}

		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task hDrive() {
	while(true) {
		motor[FrontL]  = C1LX + C1LY;
		motor[FrontR] = C1LX - C1LY;
		motor[BackL]  = C1LX + C1LY;
		motor[BackR] = C1LX - C1LY;
		motor[HMotor] = C1RX ;
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task main(){
	startTask(hDrive);
	startTask(flyLift);
	while(true) {
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}
