#pragma config(Motor,  port2,           FrontL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BackL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FrontR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BackR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LIFT,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

task liftControl()
{
	while(1){
		//Run Claw
		if((vexRT[Btn6U] == 1))
		{
			motor[LIFT]= 70;
		}
		else if((vexRT[Btn6D] == 1))
		{
			motor[LIFT]= -70;
		}
		else{
			motor[LIFT] = 0;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task tDrive() {
	while(true) {
		motor[FrontL]  = C1LY;
		motor[FrontR] = C1LY;
		motor[BackL]  = C1LY;
		motor[BackR] = C1LY;
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task main(){
	startTask(tDrive);
	startTask(liftControl);
	while(true) {
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}
