#pragma config(Sensor, dgtl1,  limitT,         sensorTouch)
#pragma config(Sensor, dgtl2,  limitB,         sensorTouch)
#pragma config(Motor,  port1,           FrontR,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BackL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LIFT,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CLAW,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BackR,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]


task clawControl()
{
	while(1){
		//Run Claw
		if((vexRT[Btn5U] == 1))
		{
			motor[CLAW]= -70;
		}
		else if((vexRT[Btn5D] == 1))
		{
			motor[CLAW]= 70;
		}
		else{
			motor[CLAW] = 0;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task liftControl()
{
	while(1){
		//Run Claw
		if((vexRT[Btn6U] == 1)&&(!SensorValue[limitT]))
		{
			motor[LIFT]= 70;
		}
		else if((vexRT[Btn6D] == 1)&&(!SensorValue[limitB]))
		{
			motor[LIFT]= -70;
		}
		else{
			motor[LIFT] = 0;
		}
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task tDrive() {
	while(true) {
		motor[FrontL]  = C1LY;
		motor[FrontR] = -C1RY;
		motor[BackL]  = C1LY;
		motor[BackR] = -C1RY;
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}

task main(){
	startTask(tDrive);
	startTask(liftControl);
	startTask(clawControl);
	while(true) {
		// Motor values can only be updated every 20ms
		wait10Msec(2);
	}
}
